### ISSUE TITLE
Document the cPanel::APIClient::Response::UAPI Class

### ISSUE THREAD

**Issue by rwp0** [cpanel/p5-cPanel-APIClient#6]
There's no documentation for the response object returned from UAPI.

https://metacpan.org/pod/cPanel::APIClient::Response::UAPI

In particular it doesn't have the [`get_error`](https://metacpan.org/pod/cPanel::APIClient::Response::WHM1#$thing-=-OBJ-%3Eget_data()) method as with [WHM response](https://metacpan.org/pod/cPanel::APIClient::Response::WHM1#$thing-=-OBJ-%3Eget_data()).

From the CPAN source https://metacpan.org/dist/cPanel-APIClient/source/lib/cPanel/APIClient/Response/UAPI.pm:

We can see the are following methods defined:

```perl
sub succeeded {
    my ($self) = @_;
 
    return $self->{'status'} ? 1 : 0;
}
 
sub get_data {
    my ($self) = @_;
 
    die "Request failed; cannot get_data()!" if !$self->{'status'};
 
    return $self->{'data'};
}
 
sub get_errors_as_string {
    my ($self) = @_;
 
    return join( $/, $self->get_errors() );
}
 
sub get_errors {
    my ($self) = @_;
 
    return $self->_get_list('errors');
}
 
sub get_warnings {
    my ($self) = @_;
 
    return $self->_get_list('warnings');
}
 
sub get_messages {
    my ($self) = @_;
 
    return $self->_get_list('messages');
}
 
sub _get_list {
    my ( $self, $name ) = @_;
 
    Call::Context::must_be_list();
 
    return $self->{$name} ? @{ $self->{$name} } : ();
}
```

But are they public and (how) should we be using them?

Thanks

**Comment by rwp0** [comment]
In particular I'm trying to achieve this with UAPI (more precisely via `call_cpanel_uapi`):

```perl
    if ( $response -> get_error ) { # returns undef if succeeded (no errors)
      p $response -> get_error;
    }
    else {
      p $response -> get_data;
    }
```

But since there's no documentation, I don't know how to proceed.

**Comment by rwp0** [comment]
> In particular I'm trying to achieve this with UAPI (more precisely via `call_cpanel_uapi`):
> 
> ```perl
>     if ( $response -> get_error ) { # returns undef if succeeded (no errors)
>       p $response -> get_error;
>     }
>     else {
>       p $response -> get_data;
>     }
> ```
> 
> But since there's no documentation, I don't know how to proceed.

Is it doable like that below?

```perl
    if ( $response -> succeeded ) {
      p $response -> get_data;
    }
    else {
      p $response -> get_errors_as_string;
    }
```

**Comment by FGasper** [comment]
Version 0.09 is now on CPAN: https://metacpan.org/pod/cPanel::APIClient
