### ISSUE TITLE
Test suite fails on fedora 36 + Ubuntu 22.04

### ISSUE THREAD

**Issue by eserte** [cpanel/p5-cPanel-APIClient#8]
See subject. A sample fail report at CPAN Testers: http://www.cpantesters.org/cpan/report/1753d98c-4ffa-11ed-9eb5-832c6e8775ea

Just a wild guess: maybe there's a SSL incompatibility on newer systems?

**Comment by FGasper** [comment]
Hmm, passes in a container: https://github.com/FGasper/p5-cPanel-APIClient/actions/runs/3303148423/jobs/5450740972

**Comment by eserte** [comment]
I see a lot of skips there...

**Comment by FGasper** [comment]
I was able to repro & fix the issue, but it looks like potentially a bug somewhere in the Perl SSL modules. I need to dig further.

**Comment by FGasper** [comment]
@eserte PR submitted.

I _suspect_ there’ll be breakage in other CPAN modules. IO::Socket::SSL’s intent is to follow the same semantics as a plain TCP connection, but if this workflow:
- shutdown(SHUT_RD)
- write
- 1 while read
- close

… triggers failures, then that violates the abstraction.

**Comment by FGasper** [comment]
Hm. This looks more like a behaviour change in either OpenSSL or TLS 1.3: mimicking TCP half-close over TLS is apparently a problem now.

So basically, shutdown() seems like a faux pas with TLS. Hrm.

**Comment by FGasper** [comment]
Fix merged; new CPAN release will be forthcoming.

In summary (for future-self and others!):
- In OpenSSL 3, an empty read causes a TLS shutdown to be sent.
- IO::Socket::SSL’s fast-shutdown can have the effect of “re-blessing” the socket as IO::Socket::INET.
